## Упражнения по библиотеке Numpy

In [3]:
import numpy as np

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [5]:
# Создаем случайный массив из 10 чисел от 0 до 10
arr = np.random.randint(0, 10, 10)
print("Исходный массив:", arr)

# Меняем знак у элементов, значения которых между 3 и 8
arr[(arr > 3) & (arr < 8)] *= -1
print("Массив после изменения знака:", arr)

Исходный массив: [9 5 8 2 0 5 5 1 7 2]
Массив после изменения знака: [ 9 -5  8  2  0 -5 -5  1 -7  2]


**2.** Заменить максимальный элемент случайного массива на 0

In [5]:
# Создаем случайный массив
arr = np.random.randint(0, 100, 10)  # 10 случайных чисел от 0 до 99
print("Исходный массив:", arr)

# Находим индекс максимального элемента и заменяем его на 0
max_index = np.argmax(arr)
arr[max_index] = 0
print("Массив после замены максимального элемента:", arr)

Исходный массив: [37 65 46 33  6 48 25 84 23  3]
Массив после замены максимального элемента: [37 65 46 33  6 48 25  0 23  3]


**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [7]:
# Создаем двумерный массив (список списков)
arrays = [
    np.array([1, 2, 3]),
    np.array([4, 5]),
    np.array([6, 7, 8])
]

# Получаем сетку индексов
grid = np.meshgrid(*arrays)

# Преобразуем каждый массив в одномерный и объединяем их в один массив
result = np.stack([g.ravel() for g in grid], axis=1)

print("Исходные массивы:")
for i, arr in enumerate(arrays, 1):
    print(f"Массив {i}: {arr}")

print("\nВсе комбинации:")
print(result)

Исходные массивы:
Массив 1: [1 2 3]
Массив 2: [4 5]
Массив 3: [6 7 8]

Все комбинации:
[[1 4 6]
 [1 4 7]
 [1 4 8]
 [2 4 6]
 [2 4 7]
 [2 4 8]
 [3 4 6]
 [3 4 7]
 [3 4 8]
 [1 5 6]
 [1 5 7]
 [1 5 8]
 [2 5 6]
 [2 5 7]
 [2 5 8]
 [3 5 6]
 [3 5 7]
 [3 5 8]]


**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [10]:
# Создаем тестовые массивы, пробовала делать рандомные, но так долго генерить приходиться
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12],
    [1, 4, 7],
    [2, 5, 8],
    [3, 6, 9],
    [10, 11, 12]
])

B = np.array([
    [1, 2],
    [4, 5]
])

print("Массив A (8x3):")
print(A)
print("\nМассив B (2x2):")
print(B)

# Функция для проверки, содержит ли строка из A все элементы хотя бы одной строки из B
def contains_any_row(a_row, b):
    return any(np.all(np.isin(b_row, a_row)) for b_row in B)

# Находим индексы строк, удовлетворяющих условию
mask = np.array([contains_any_row(row, B) for row in A])
result = A[mask]

print("\nСтроки A, содержащие хотя бы одну строку из B:")
print(result)

Массив A (8x3):
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [ 1  4  7]
 [ 2  5  8]
 [ 3  6  9]
 [10 11 12]]

Массив B (2x2):
[[1 2]
 [4 5]]

Строки A, содержащие хотя бы одну строку из B:
[[1 2 3]
 [4 5 6]]


**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [11]:
# Создаем тестовую матрицу 10x3
matrix = np.array([
    [1, 2, 3],
    [4, 4, 4],
    [5, 6, 5],
    [7, 7, 8],
    [9, 9, 9],
    [1, 2, 1],
    [3, 3, 3],
    [4, 5, 6],
    [7, 7, 7],
    [8, 9, 10]
])

print("Исходная матрица:")
print(matrix)

# Находим строки, где не все элементы равны между собой
# Для этого проверяем, что минимальный и максимальный элементы в строке не равны
result = matrix[matrix.max(axis=1) != matrix.min(axis=1)]

print("\nСтроки с неравными значениями:")
print(result)

Исходная матрица:
[[ 1  2  3]
 [ 4  4  4]
 [ 5  6  5]
 [ 7  7  8]
 [ 9  9  9]
 [ 1  2  1]
 [ 3  3  3]
 [ 4  5  6]
 [ 7  7  7]
 [ 8  9 10]]

Строки с неравными значениями:
[[ 1  2  3]
 [ 5  6  5]
 [ 7  7  8]
 [ 1  2  1]
 [ 4  5  6]
 [ 8  9 10]]


**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [8]:
# Создаем тестовый массив с повторяющимися строками
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [1, 2, 3],  # Дубликат первой строки
    [7, 8, 9],
    [4, 5, 6],  # Дубликат второй строки
    [10, 11, 12],
    [7, 8, 9],  # Дубликат четвертой строки
    [1, 2, 3]   # Еще один дубликат первой строки
])

print("Исходный массив:")
print(arr)

# Используем np.unique с параметром axis=0 для поиска уникальных строк
# return_index=True возвращает индексы первых вхождений уникальных строк
unique_rows, indices = np.unique(arr, axis=0, return_index=True)

# Сортируем индексы, чтобы сохранить исходный порядок строк
result = arr[np.sort(indices)]

print("\nМассив без повторяющихся строк:")
print(result)

Исходный массив:
[[ 1  2  3]
 [ 4  5  6]
 [ 1  2  3]
 [ 7  8  9]
 [ 4  5  6]
 [10 11 12]
 [ 7  8  9]
 [ 1  2  3]]

Массив без повторяющихся строк:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [18]:
# Без NumPy
def diagonal_product(matrix):
    # Получаем диагональные элементы
    diag = [row[i] for i, row in enumerate(matrix) if i < len(row)]
    # Вычисляем произведение ненулевых элементов
    product = 1
    for num in diag:
        if num != 0:
            product *= num
    return product

# Пример использования
X = [[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]
print(diagonal_product(X))

3


In [17]:
# C NumPy
def diagonal_product(matrix):
    # Получаем диагональные элементы
    diag = np.diag(matrix)
    # Вычисляем произведение ненулевых элементов
    return np.prod(diag[diag != 0])

# Пример использования
X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])
print(diagonal_product(X))

3


* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [15]:
# Без NumPy
def multiset(x, y):
    from collections import Counter
    return Counter(x) == Counter(y)

# Пример использования
x = [1, 2, 2, 4]
y = [4, 2, 1, 2]
print(multiset(x, y))

True


In [16]:
# C NumPy
def multiset(x, y):
    return np.array_equal(np.sort(x), np.sort(y))

# Пример использования
x = np.array([1, 2, 2, 4])
y = np.array([4, 2, 1, 2])
print(multiset(x, y))

True


* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [19]:
# Без NumPy
def max_after_zero(x):
    return max([x[i] for i in range(1, len(x)) if x[i-1] == 0])

# Пример использования
x = [6, 2, 0, 3, 0, 0, 5, 7, 0]
print(max_after_zero(x))

5


In [20]:
# C NumPy
def max_after_zero(x):
    return x[1:][x[:-1] == 0].max()

# Пример использования
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
print(max_after_zero(x))

5


* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [21]:
# Без NumPy
def rle(x):
    if not x:
        return [], []

    values = [x[0]]
    counts = [1]

    for num in x[1:]:
        if num == values[-1]:
            counts[-1] += 1
        else:
            values.append(num)
            counts.append(1)

    return values, counts

# Пример использования
x = [2, 2, 2, 3, 3, 3, 5]
values, counts = rle(x)
print((values, counts))

([2, 3, 5], [3, 3, 1])


In [22]:
# C NumPy
def rle(x):
    x = np.asarray(x)
    mask = np.diff(x, prepend=np.nan) != 0
    values = x[mask]
    counts = np.diff(np.where(np.concatenate([mask, [True]]))[0])
    return values, counts

# Пример использования
x = np.array([2, 2, 2, 3, 3, 3, 5])
values, counts = rle(x)
print((values, counts))

(array([2, 3, 5]), array([3, 3, 1]))


* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [23]:
import math

def euclidean_distances(X, Y):

    n = len(X)
    m = len(Y)
    dist_matrix = [[0.0] * m for _ in range(n)]

    for i in range(n):
        for j in range(m):
            # Сумма квадратов разностей координат
            squared_dist = sum((a - b) ** 2 for a, b in zip(X[i], Y[j]))
            dist_matrix[i][j] = math.sqrt(squared_dist)

    return dist_matrix

# Пример использования
X = [[1, 2], [3, 4], [5, 6]]  # 3 точки в 2D
Y = [[1, 1], [2, 2], [3, 3], [4, 4]]  # 4 точки в 2D

# Вычисляем расстояния
distances = euclidean_distances(X, Y)
print("Матрица расстояний (без NumPy):")
for row in distances:
    print([round(d, 2) for d in row])

Матрица расстояний (без NumPy):
[1.0, 1.0, 2.24, 3.61]
[3.61, 2.24, 1.0, 1.0]
[6.4, 5.0, 3.61, 2.24]


In [25]:
import numpy as np

def euclidean_distances(X, Y):

    # Преобразуем в массивы NumPy, если это еще не сделано
    X = np.array(X)
    Y = np.array(Y)

    # Используем формулу: √(Σ(x_i - y_j)²)
    # Через broadcasting: (n, 1, d) - (1, m, d) = (n, m, d)
    # Затем суммируем по последней оси и извлекаем корень
    return np.sqrt(np.sum((X[:, np.newaxis, :] - Y[np.newaxis, :, :])**2, axis=2))

# Те же данные, что и в первом примере
X = np.array([[1, 2], [3, 4], [5, 6]])
Y = np.array([[1, 1], [2, 2], [3, 3], [4, 4]])

# Вычисляем расстояния
distances_np = euclidean_distances(X, Y)
print("\nМатрица расстояний (с NumPy):")
print(np.round(distances_np, 2))

# Проверка эквивалентности с первым методом
print("\nРезультаты совпадают:",
      np.allclose(np.array(distances), distances_np))


Матрица расстояний (с NumPy):
[[1.   1.   2.24 3.61]
 [3.61 2.24 1.   1.  ]
 [6.4  5.   3.61 2.24]]

Результаты совпадают: True


_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [27]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [28]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [29]:
# Среднее количество калорий
average_calories = np.mean(calorie_stats)
print(f"Среднее количество калорий: {average_calories:.2f}")

# Разница с CrunchieMunchies (60 калорий)
difference = average_calories - 60
print(f"Разница со средним: {difference:.2f} калорий")

Среднее количество калорий: 106.88
Разница со средним: 46.88 калорий


3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [32]:
calorie_stats_sorted = np.sort(calorie_stats)
print("Отсортированные данные калорийности:")
print(calorie_stats_sorted)

Отсортированные данные калорийности:
[ 50.  50.  50.  70.  70.  80.  90.  90.  90.  90.  90.  90.  90. 100.
 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 120. 120. 120. 120. 120. 120. 120. 120. 120. 120. 130.
 130. 140. 140. 140. 150. 150. 160.]


4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [42]:
median_calories = np.median(calorie_stats)
print(f"Медиана калорийности: {median_calories}")

Медиана калорийности: 110.0


5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [34]:
# Расчет процентилей
percentiles = np.percentile(calorie_stats, range(0, 101, 10))
print("Процентили (0-100% с шагом 10%):")
for p, val in zip(range(0, 101, 10), percentiles):
    print(f"{p}%: {val:.2f} калорий")

# Находим наименьший процентиль > 60
for p in range(1, 101):
    if np.percentile(calorie_stats, p) > 60:
        nth_percentile = p
        break

print(f"Наименьший процентиль >60: {nth_percentile}%")

Процентили (0-100% с шагом 10%):
0%: 50.00 калорий
10%: 90.00 калорий
20%: 100.00 калорий
30%: 100.00 калорий
40%: 110.00 калорий
50%: 110.00 калорий
60%: 110.00 калорий
70%: 110.00 калорий
80%: 120.00 калорий
90%: 124.00 калорий
100%: 160.00 калорий
Наименьший процентиль >60: 4%


6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [40]:
more_calories = np.mean(calorie_stats > 60) * 100
print(f"Процент хлопьев с калорийностью >60: {more_calories:.2f}%")

Процент хлопьев с калорийностью >60: 96.10%


7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [39]:
calorie_std = np.std(calorie_stats, ddof=1)
print(f"Стандартное отклонение: {calorie_std:.2f} калорий")

Стандартное отклонение: 19.48 калорий


8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

In [41]:
print("\nАнализ данных о калорийности хлопьев:")
print(f"1. Средняя калорийность: {average_calories:.1f} калорий")
print(f"2. Медианная калорийность: {median_calories:.1f} калорий")
print(f"3. {more_calories:.1f}% брендов содержат больше 60 калорий")
print(f"4. Стандартное отклонение: {calorie_std:.2f} калорий")

print("\nКлючевые выводы для маркетинга:")
print("- CrunchieMunchies содержат значительно меньше калорий, чем у большинства конкурентов.")
print(f"- Продукт попадает в топ-{nth_percentile}% по низкой калорийности.")
print("- Высокий разброс данных (стандартное отклонение) показывает, что CrunchieMunchies выделяются на фоне конкурентов.")


Анализ данных о калорийности хлопьев:
1. Средняя калорийность: 106.9 калорий
2. Медианная калорийность: 110.0 калорий
3. 96.1% брендов содержат больше 60 калорий
4. Стандартное отклонение: 19.48 калорий

Ключевые выводы для маркетинга:
- CrunchieMunchies содержат значительно меньше калорий, чем у большинства конкурентов.
- Продукт попадает в топ-4% по низкой калорийности.
- Высокий разброс данных (стандартное отклонение) показывает, что CrunchieMunchies выделяются на фоне конкурентов.
